---
title: "Home Energy Analysis"
output: html_notebook
---


```{r}

library(shiny)
library(shinydashboard)
library(tidyverse)
library(sf)
library(here)
library(scales)
library(leaflet)
library(htmltools)
library(janitor)
```

#Reading in cleaned file
```{r}
home_energy <- read_csv(here("clean_data/home_energy.csv"))
```



#Table of the means per town and postcode for each year, quarter
```{r}
energy_means <- home_energy %>% 
  group_by(ca, ca_name, year) %>% 
  summarise(mean_co2_pfa = round(mean(co2_emissions_per_floor_area), digits = 2),
            mean_primary_energy = round(mean(primary_energy), digits = 2),
            mean_current_emissions = round(mean(current_emissions_t_co2_yr), digits = 2))
energy_means
```



#Visualising mean_co2_emissions_current_per_floor_area for cities from 2012 to 2020
```{r}

mean_co2_emissions <- energy_means %>% 
  group_by(postcode, year) %>% 
  summarise(mean_co2_emissions_pfa = round(mean(mean_co2_pfa), digits = 2))

mean_co2_emissions

```

```{r}
mean_co2_emissions %>% 
  ggplot() +
  aes(x = mean_co2_emissions_pfa, y = ca_name) +
  geom_col(fill = "dark green") +
  theme_minimal() +
  labs(
    y = "Council Area",
    x = "Mean CO2 Emissions Per Current Floor Area (kg CO2/m^2/Year)",
    title = "Mean CO2 Emissions Current Floor Area of Homes by Council Area",
    subtitle = "2012 - 2020"
  ) +
  theme(axis.text.x = element_text(angle=45,hjust=1)) 

```



# Visualising Mean Primary Energy Indicator of Homes by Council Area

```{r}

mean_primary_energy_all <- energy_means %>% 
  group_by(ca_name) %>% 
  summarise(mean_primary_energy = round(mean(mean_primary_energy), digits = 2))

mean_primary_energy_all
```

```{r}
mean_primary_energy_all %>% 
  ggplot() +
  aes(x = mean_primary_energy, y = ca_name) +
  geom_col(fill = "dark green") +
  theme_minimal() +
  labs(
    y = "Council Area",
    x = "Mean Primary Energy Indicator (kWh/m^2/yr)",
    title = "Mean Primary Energy Indicator of Homes by Council Area",
    subtitle = "2012 - 2020"
  ) +
  theme(axis.text.x = element_text(angle=45,hjust=1)) 

mean_primary_energy_all
```


# Visualising Mean Current Emissions of Homes by Council Area (Tonnes CO2/Year) 
```{r}
mean_current_emissions <- energy_means %>% 
  group_by(ca_name) %>% 
  summarise(mean_current_emissions_all = round(mean(mean_current_emissions), digits = 2))

mean_current_emissions

mean_current_emissions %>% 
  ggplot() +
  aes(x = mean_current_emissions_all, y = ca_name) +
  geom_col(fill = "dark green") +
  theme_minimal() +
  labs(
    y = "Council Area",
    x = "Mean Current Emissions (Tonnes CO2/Year)",
    title = "Mean Current Emissions of Homes by Council Area",
    subtitle = "2012 - 2020"
  ) +
  theme(axis.text.x = element_text(angle=45,hjust=1)) 
```

```{r}
#Energy means all time
energy_means_all <- energy_means %>% 
  group_by(ca, ca_name) %>% 
  summarise(mean_co2 = round(mean(mean_co2_pfa), digits = 2),
            mean_primary = round(mean(mean_primary_energy), digits = 2),
            mean_current_emissions_all = round(mean(mean_current_emissions), digits = 2))
  
```



Map

```{r}
#adding labels for map
energy_means_labels <- energy_means_all %>%
  mutate(
    leaflet_lb = paste(
      "<b>",
      ca_name,
      "</b>" ,
      br(),
      "Mean Co2 Emissions: ",
      mean_co2,
      br(),
      "from 2012 to 2020")
  )
```


Map
```{r}
#Reading in shapefile
la_map_scotland <- st_read(here("clean_data/scotland_map_files/scotland_council_areas_map.shp")) %>%  
  clean_names()
la_map_scotland
```


Map

```{r}
#joining home energy data with shapefile
la_scotland_home_energy <- la_map_scotland %>%
  left_join(energy_means_labels, by = c("area_cod_1" = "ca"))

la_scotland_home_energy
```

#Mean CO2 Emissions
```{r}
# Set pallete for mean co2_emissions across households in Scotland
pal_co2_emissions <- colorNumeric(palette = "YlGnBu",
                         domain = la_scotland_home_energy$mean_co2)


#Set boundaries of Scotland
bbox <- st_bbox(la_scotland_home_energy) %>%
  as.vector()
```


```{r}
leaflet(la_scotland_home_energy) %>%
      #adding base tiles
      addProviderTiles("CartoDB.Positron") %>%
      #setting bounds of map
      fitBounds(bbox[1], bbox[2], bbox[3], bbox[4]) %>%
      setView(lat = 56, lng = -4.3, zoom = 6) %>% 
  addPolygons(
    color = "grey", weight = 1,
    fillColor = ~ pal_co2_emissions(mean_co2), fillOpacity = 0.5
  ) %>%
  addLegend(
    pal = pal_co2_emissions, values = ~mean_co2, opacity = 0.5,
    title = "Average CO2 Emissions", position = "bottomright"
  )
```

```{r}
potential_current_emissions <- home_energy %>% 
  #select(year, potential_co2, current_emissions_t_co2_yr) %>% 
  group_by(year, potential_co2, current_emissions_t_co2_yr) %>% 
    summarise(mean_current_emissions_all = round(mean(current_emissions_t_co2_yr), digits = 2),
              mean_potential_emissions = round(exp(sum(log(potential_co2[potential_co2 > 0]), na.rm=TRUE) / length(potential_co2)), digits = 2))
  potential_current_emissions
```
```{r}
#Potential by Area
home_energy %>% 
      group_by(ca_name, year) %>% 
      summarise(mean_potential_emissions = round(exp(sum(log(potential_co2[potential_co2 > 0]), na.rm=TRUE) / length(potential_co2)), digits = 2)) %>% 
      ggplot() +
      aes(x = reorder(ca_name, mean_potential_emissions), y = mean_potential_emissions) +
      geom_col(fill = "#3c8dbc") +
      coord_flip() +
      theme_minimal() +
      labs(
        y = "Tonnes per Year",
        x = "Local Authority Area"
        #title = "Mean Potential Emissions of Homes"
      ) +
      theme(axis.text.x = element_text(angle=45,hjust=1)) 
```


```{r}
home_energy_zone %>% 
      group_by(tenure, year) %>% 
      summarise(mean_current_emissions = round(mean(current_emissions_t_co2_yr), digits = 2)) %>% 
      ggplot() +
      aes(x = year, y = mean_current_emissions, colour = tenure) +
      geom_line(color = "#3c8dbc") +
      geom_point(color = "#3c8dbc") +
      theme_minimal() +
      labs(
        y = "Tonnes per Year",
        x = "Year",
        #title = "Mean Current Emissions of Homes",
        subtitle = "2012 - 2020"
      ) +
      theme(axis.text.x = element_text(angle=45,hjust=1)) 
```


```{r}
#Potential Emissions Overall Scotland
    potential_home_energy <- home_energy %>%
      group_by(year) %>% 
      summarise(mean_potential_emissions = round(exp(sum(log(potential_co2[potential_co2 > 0]), na.rm=TRUE) / length(potential_co2)), digits = 2)) 

potential_home_energy %>% 
      ggplot() +
      aes(x = year, y = mean_potential_emissions) +
      geom_line(color = "#3c8dbc") +
      geom_point(color = "#3c8dbc") +
      theme_minimal() +
      labs(
        y = "Tonnes per Year",
        x = "Year",
        title = "Potential CO2 Emissions"
      ) +
      theme(axis.text.x = element_text(angle=45,hjust=1)) 

potential_home_energy
```

```{r}
#Current Emissions Overall Scotland
    current_home_energy <- home_energy %>%
      group_by(year) %>% 
      summarise(mean_current_emissions = round(mean(current_emissions_t_co2_yr), digits = 2)) 

current_home_energy %>% 
      ggplot() +
      aes(x = year, y = mean_current_emissions) +
      geom_line(color = "#3c8dbc") +
      geom_point(color = "#3c8dbc") +
      theme_minimal() +
      labs(
        y = "Tonnes per Year",
        x = "Year",
        title = "Current CO2 Emissions"
      ) +
      theme(axis.text.x = element_text(angle=45,hjust=1)) 

current_home_energy
```

```{r}
current_potential = merge(current_home_energy, potential_home_energy, by="year")
head(current_potential)
```

```{r}
current_potentialMelted <- reshape2::melt(current_potential, id.var='year')
head(current_potentialMelted)
```

```{r}
cols <- c("#3c8dbc", "#5cbd9d")

ggplot(current_potentialMelted, aes(x=year, y=value, col=variable)) +
      geom_line() +
      geom_point(size=2, shape=21, fill="white") +
    scale_colour_manual(values = cols,
                        name = NULL,
                        labels = c("Average Current Emissions", "Average Potential Emissions")) +
      theme_minimal() +
      labs(
        y = "Tonnes per Year",
        x = "Year",
        title = "Current vs Potential CO2 Emissions"
      ) +
      theme(axis.text.x = element_text(angle=45,hjust=1), legend.position = "bottom") 
```

